"""
Configuration and Constants.
Stores application-wide settings, file paths, and translation strings.
"""
from pathlib import Path
import sys
import os

# --- Constants and Configuration ---
APP_NAME = "Core Renamer"
APP_VERSION = "1.0.0"

# Determine the directory where the script is running to store data files
DATA_DIR = Path(__file__).resolve().parent

# Paths for persistent data storage
HISTORY_FILE = DATA_DIR / "rename_history.json"
SETTINGS_FILE = DATA_DIR / "app_settings.json"
LOG_FILE = DATA_DIR / "app.log"

# File type definitions for the filter dropdown
# Used to categorize files in logic and suggestions
FILE_TYPE_EXTENSIONS = {
    "Images": ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp', '.tiff', '.svg'],
    "Videos": ['.mp4', '.mkv', '.avi', '.mov', '.wmv', '.flv'],
    "Documents": ['.pdf', '.doc', '.docx', '.txt', '.xlsx', '.pptx', '.odt', '.ods', '.odp'],
    "Audio": ['.mp3', '.wav', '.flac', '.aac', '.ogg', '.m4a'],
    "Projects": ['.prproj', '.aep', '.psd', '.ai', '.veg', '.drp', '.aup3', '.cpr'],
    "Archives": ['.zip', '.rar', '.7z', '.tar', '.gz'],
}

# Dictionary containing all UI text for localization
TRANSLATIONS = {
    "en": {
        "app_title": "Core Renamer",
        "select_folder": "Select Folder...",
        "exit": "Exit",
        "file": "File",
        "edit": "Edit",
        "tools": "Tools",
        "help": "Help",
        "reset_fields": "Reset Fields",
        "history_undo": "History / Undo",
        "about": "About",
        "target_folder": "Target Folder",
        "no_folder": "No folder selected",
        "browse": "Browse...",
        "files_list": "Files List",
        "filters": "Filters",
        "file_type": "File Type:",
        "contains_text": "Contains Text:",
        "renaming_rules": "Renaming Rules",
        "new_base_name": "New Base Name:",
        "start_number": "Start Number:",
        "preview": "Preview",
        "rename_files": "Rename Files",
        "ready": "Ready.",
        "toggle_theme": "Toggle Theme",
        "generating_preview": "Generating preview...",
        "preview_generated": "Preview generated.",
        "renaming_progress": "Renaming in progress...",
        "processing": "Processing [{}/{}] : {}",
        "complete": "Operation complete. Renamed {} files in {:.2f}s.",
        "success": "Success",
        "error": "Error",
        "warning": "Warning",
        "confirm_rename": "Are you sure you want to rename {} files in '{}' to '{}...'?",
        "confirm_undo": "Undo rename of {} files from session dated {}?",
        "undo_incomplete": "Restored {} files.\n{} errors occurred. Check logs for details.",
        "rename_incomplete": "Renamed {} files.\n{} errors occurred. Check logs for details.",
        "undo_successful": "Successfully restored {} files.",
        "history_cleared": "History has been cleared.",
        "about_text": "{} v{}\n\nThe ultimate organization tool for Content Creators.\nManage your footage, assets, and project files efficiently.\n\n",
        "no_files_match": "No files match the current filters.",
        "no_files_rename": "No files to rename with given filters.",
        "enter_base_name": "Please enter a new base name!",
        "select_folder_first": "Please select a folder first!",
        "preview_title": "Preview - {} files",
        "export_csv": "Export to CSV",
        "export_success": "Preview exported successfully!",
        "export_fail": "Failed to export: {}",
        "matching_files": "Matching Files: {}",
        "current_name": "Current Name",
        "new_name": "New Name",
        "history_title": "History & Undo Manager",
        "select_session": "Select a session to view details or Undo.",
        "time": "Time",
        "folder": "Folder",
        "files_renamed": "Files Renamed",
        "undo_selected": "Undo Selected Session",
        "close": "Close",
        "clear_history": "Clear History",
        "confirm_clear": "Are you sure you want to delete all history records?\nThis action cannot be undone.",
        "language": "Language",
        "english": "English",
        "arabic": "Arabic",
        "tooltip_contains": "Only rename files containing this text (case-insensitive)",
        "tooltip_base": "Pattern: {original}, {num}, {date} (e.g. Trip_{date}_{num})",
        "tooltip_start": "The starting number for the file sequence",
        "completed_errors": "Completed with Errors",
        "undo_incomplete_title": "Undo Incomplete",
        "undo_success_title": "Undo Successful",
        "confirm_undo_title": "Confirm Undo",
        "confirm_rename_title": "Confirm Rename",
        "confirm_clear_title": "Confirm Clear",
        "info": "Info",
        "no_history": "No rename history found!",
        "help_guide": "Quick Guide",
        "guide_text": "Welcome to {} v{}!\n\nQuick Start Guide:\n1. Select Folder: Click 'Browse' to choose your files.\n2. Filter: (Optional) Select file type or text filter.\n3. Naming: Enter a Base Name or pick a Smart Suggestion.\n   • Tip: Use {{original}} to keep the old name.\n   • Tip: Use {{num}} to set number position.\n4. Preview: Check the 'Files List' to see changes.\n5. Rename: Click 'Rename Files' to apply.\n6. Undo: Use 'History / Undo' to revert changes.",
        "smart_suggestions": "Smart Suggestions",
        "suggestion_folder": "📂 Folder",
        "suggestion_date": "📅 Date",
        "suggestion_text": "🔤 Text",
        "suggestion_type": "📄 Type",
        "suggestion_random": "🔀 Random",
        "suggestion_reason": "Reason: {}",
        "welcome_title": "Welcome to Core Renamer",
        "welcome_text": "Thank you for installing Core Renamer!\n\nThis tool helps you organize your files efficiently.\n\nTo get started:\n1. Select a Folder.\n2. Choose Filters (optional).\n3. Enter a Name or use Smart Suggestions.\n\nCheck the 'Help' menu for a Quick Guide."
    },
    "ar": {
        "app_title": "Core Renamer - منظم الملفات",
        "select_folder": "اختر مجلداً...",
        "exit": "خروج",
        "file": "ملف",
        "edit": "تحرير",
        "tools": "أدوات",
        "help": "مساعدة",
        "reset_fields": "إعادة تعيين الحقول",
        "history_undo": "السجل / تراجع",
        "about": "حول",
        "target_folder": "المجلد المستهدف",
        "no_folder": "لم يتم اختيار مجلد",
        "browse": "تصفح...",
        "files_list": "قائمة الملفات",
        "filters": "تصفية",
        "file_type": "نوع الملف:",
        "contains_text": "يحتوي على نص:",
        "renaming_rules": "قواعد التسمية",
        "new_base_name": "الاسم الأساسي الجديد:",
        "start_number": "رقم البداية:",
        "preview": "معاينة",
        "rename_files": "إعادة تسمية الملفات",
        "ready": "جاهز.",
        "toggle_theme": "تغيير المظهر",
        "generating_preview": "جاري إنشاء المعاينة...",
        "preview_generated": "تم إنشاء المعاينة.",
        "renaming_progress": "جاري إعادة التسمية...",
        "processing": "جاري معالجة [{}/{}] : {}",
        "complete": "اكتملت العملية. تم إعادة تسمية {} ملف في {:.2f} ثانية.",
        "success": "نجاح",
        "error": "خطأ",
        "warning": "تحذير",
        "confirm_rename": "هل أنت متأكد من إعادة تسمية {} ملف في '{}' لتصبح '{}...'؟",
        "confirm_undo": "تراجع عن تسمية {} ملف من الجلسة بتاريخ {}؟",
        "undo_incomplete": "تم استعادة {} ملف.\nحدثت {} أخطاء. تحقق من السجلات للتفاصيل.",
        "rename_incomplete": "تم إعادة تسمية {} ملف.\nحدثت {} أخطاء. تحقق من السجلات للتفاصيل.",
        "undo_successful": "تم استعادة {} ملف بنجاح.",
        "history_cleared": "تم مسح السجل.",
        "about_text": "{} v{}\n\nالأداة المثالية للمبدعين لتنظيم اللقطات والملفات والمشاريع بسرعة وكفاءة.\n\n",
        "no_files_match": "لا توجد ملفات تطابق عوامل التصفية الحالية.",
        "no_files_rename": "لا توجد ملفات لإعادة تسميتها باستخدام عوامل التصفية المعطاة.",
        "enter_base_name": "الرجاء إدخال اسم أساسي جديد!",
        "select_folder_first": "الرجاء اختيار مجلد أولاً!",
        "preview_title": "معاينة - {} ملف",
        "export_csv": "تصدير إلى CSV",
        "export_success": "تم تصدير المعاينة بنجاح!",
        "export_fail": "فشل التصدير: {}",
        "matching_files": "الملفات المطابقة: {}",
        "current_name": "الاسم الحالي",
        "new_name": "الاسم الجديد",
        "history_title": "مدير السجل والتراجع",
        "select_session": "اختر جلسة لعرض التفاصيل أو التراجع.",
        "time": "الوقت",
        "folder": "المجلد",
        "files_renamed": "الملفات التي تم تغيير اسمها",
        "undo_selected": "تراجع عن الجلسة المحددة",
        "close": "إغلاق",
        "clear_history": "مسح السجل",
        "confirm_clear": "هل أنت متأكد من حذف جميع سجلات المحفوظات؟\nلا يمكن التراجع عن هذا الإجراء.",
        "language": "اللغة",
        "english": "الإنجليزية",
        "arabic": "العربية",
        "tooltip_contains": "إعادة تسمية الملفات التي تحتوي على هذا النص فقط",
        "tooltip_base": "النمط: {original}, {num}, {date} (مثال: رحلة_{date}_{num})",
        "tooltip_start": "رقم البداية لتسلسل الملفات",
        "completed_errors": "اكتمل مع وجود أخطاء",
        "undo_incomplete_title": "تراجع غير مكتمل",
        "undo_success_title": "نجاح التراجع",
        "confirm_undo_title": "تأكيد التراجع",
        "confirm_rename_title": "تأكيد إعادة التسمية",
        "confirm_clear_title": "تأكيد المسح",
        "info": "معلومات",
        "no_history": "لم يتم العثور على سجل إعادة تسمية!",
        "help_guide": "دليل سريع",
        "guide_text": "مرحباً بك في {} v{}!\n\nدليل البدء السريع:\n1. اختر المجلد: اضغط 'تصفح' لاختيار ملفاتك.\n2. تصفية: (اختياري) حدد نوع الملف أو ابحث بالنص.\n3. التسمية: أدخل اسماً جديداً أو اختر اقتراحاً ذكياً.\n   • تلميح: استخدم {{original}} للإبقاء على الاسم القديم.\n   • تلميح: استخدم {{num}} لتحديد مكان الرقم.\n4. معاينة: راجع 'قائمة الملفات' لرؤية التغييرات.\n5. نفذ: اضغط 'إعادة تسمية الملفات'.\n6. تراجع: استخدم 'السجل / تراجع' عند الحاجة.",
        "smart_suggestions": "اقتراحات ذكية",
        "suggestion_folder": "📂 مجلد",
        "suggestion_date": "📅 تاريخ",
        "suggestion_text": "🔤 نص",
        "suggestion_type": "📄 نوع",
        "suggestion_random": "🔀 عشوائي",
        "suggestion_reason": "السبب: {}",
        "welcome_title": "مرحباً بك في Core Renamer",
        "welcome_text": "شكراً لتثبيت Core Renamer!\n\nتساعدك هذه الأداة على تنظيم ملفاتك بكفاءة.\n\nللبدء:\n1. اختر مجلداً.\n2. حدد عوامل التصفية (اختياري).\n3. أدخل اسماً أو استخدم الاقتراحات الذكية.\n\nتحقق من قائمة 'مساعدة' للحصول على دليل سريع."
    }
}